export const GET_ALL_PRODUCTS="GET_ALL-PRODUCTS"
export const GET_UNSOLD_PRODUCTS='GET_UNSOLD_PRODUCTS'
export const POST_PRODUCT='POST_PRODUCT'
export const PURCHASE_PRODUCTS='PURCHASE_PRODUCTS'
export const MY_PRODUCTS='MY_PRODUCTS'