export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const USER = 'USER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const POST_BASIC_INFO = 'POST_BASIC_INFO';
export const POST_BASIC_INFO_PENDING = 'POST_BASIC_INFO_PENDING';

export const POST_EDUCATION = 'POST_EDUCATION';
export const POST_EDUCATION_PENDING = 'POST_EDUCATION_PENDING';

export const POST_WORK = 'POST_WORK';
export const POST_WORK_PENDING = 'POST_WORK_PENDING';

export const POST_SKILLS_PENDING='POST_SKILLS_PENDING'

export const POST_PROJECT_PENDING='POST_PROJECT_PENDING'

export const POST_ACHIEVEMENT_PENDING='POST_ACHIEVEMENT_PENDING'

export const POST_SOCIAL_PENDIN='POST_SOCIAL_PENDING'
